apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-pod
  template:
    metadata:
      labels:
        app: wordpress-pod
    spec:
      containers:
      - name: wordpress-container
        image: wordpress:latest
        env:
        - name: WORDPRESS_DB_HOST
          value: 172.31.25.126
        - name: WORDPRESS_DB_USER
          value: admin
        - name: WORDPRESS_DB_PASSWORD
          value: admin123
        - name: WORDPRESS_DB_DATABASE
          value: wordpress02
        ports:
        - containerPort: 80
