apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    targetPort: 80
    port: 80
  selector:
    app: nginx-pod
